### ISSUE TITLE
Build with gcc7

### ISSUE THREAD

**Issue by awissu** [pixlra/playuver#29]
Hi! I bumped on problem when building rpm in OBS:
```
[  118s] cd /home/abuild/rpmbuild/BUILD/playuver-0.18.1/build/app && /usr/bin/c++  -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -I/home/abuild/rpmbuild/BUILD/playuver-0.18.1/build/app/playuver_autogen/include -I/home/abuild/rpmbuild/BUILD/playuver-0.18.1/build -I/home/abuild/rpmbuild/BUILD/playuver-0.18.1 -I/home/abuild/rpmbuild/BUILD/playuver-0.18.1/app/external -isystem /usr/include/opencv -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtDBus -I/home/abuild/rpmbuild/BUILD/playuver-0.18.1/app/external/qcustomplot/. -isystem /usr/include/qt5/QtPrintSupport  -Wall -O3 -DNDEBUG -O2   -std=gnu++0x -fPIC -std=gnu++14 -o CMakeFiles/playuver.dir/FramePropertiesDock.cpp.o -c /home/abuild/rpmbuild/BUILD/playuver-0.18.1/app/FramePropertiesDock.cpp
[  118s] /home/abuild/rpmbuild/BUILD/playuver-0.18.1/app/VideoSubWindow.cpp: In member function 'Void VideoInformation::setInformationTopLeft(const QStringList&)':
[  118s] /home/abuild/rpmbuild/BUILD/playuver-0.18.1/app/VideoSubWindow.cpp:105:52: error: no matching function for call to 'QList<QStaticText>::append(const QString&)'
[  118s]        m_cTopLeftTextList.append( textLines.at( i ) );
```
See: https://build.opensuse.org/public/build/home:awissu:branches:multimedia:apps/openSUSE_Tumbleweed/x86_64/playuver/_log

**Comment by jfmcarreira** [comment]
​​
Dear Alexei,

Let me start by thanking you the interest in this software.

I will need further information to debug this error:

   - Did it build successfully in the past?
   - ​What is the Qt version that ​you are using?


T
​hat line of code has been there for a year without problem, so I do not
understand what changed. QStaticText has a constructor to create an
instance from QString.

​Attached you may find a patch that adds a cast to the given instruction.

​
--
Cumprimentos,

*João Carreira*

**Comment by awissu** [comment]
> - Did it build successfully in the past?

Yes.

>  - ​What is the Qt version that ​you are using?

5.10.0

**Comment by jfmcarreira** [comment]
Can you test the patch I sent?

If it works I can push it upstream.

--
Best regards,

João Carreira

**Comment by awissu** [comment]
> Can you test the patch I sent?

Sorry. I can't find the patch.

**Comment by jfmcarreira** [comment]
It's in my first reply.

--
Regards,

João Carreira

**Comment by awissu** [comment]
Provide a link to the attached file.

**Comment by jfmcarreira** [comment]
Sorry I forgot attachments were not published here.
 
Please find the patch on the following link: 
https://gist.github.com/jfmcarreira/eceaa3aaece2bab64260b51d2787c2a4

**Comment by awissu** [comment]
Thanks.
This patch solves the problem.

**Comment by jfmcarreira** [comment]
Do you provide regular builds of stable releases?

If so I could point to the link so more people wouls use it

**Comment by awissu** [comment]
> Do you provide regular builds of stable releases?

Yes.
Package is avaiable on https://software.opensuse.org/package/playuver

**Comment by jfmcarreira** [comment]
Ok thanks for the contribution.

I will post the link in the readme
